export const categories = [["web","Websites"],["apps","Apps"],["all","Show All"],["none","Hide All"]]

export const projectsArray = [
  {
    name: 'Online Shop',
    important: true,
    mockImage: "lesperance-kp.png",
    liveLink: "immm",
    gitLink: "imm",
    category: "web",
    image: "im",
    stack: ["NextJS,ReactJS,HTML,CSS,MongoDB,KeystoneJS,Nginx"],
    description: "This NextJS app allows the user to signup,login, find,add to cart and order products, check out prices and stock for products and services and send emails to the owner. Through KeystoneJS the owner can add/delete/edit contents from the database"
  },
  {
    name: 'Portofolio V2',
    important: true,
    mockImage: "lesperance-kp.png",
    liveLink: "immm",
    gitLink: "imm",
    category: "web",
    image: "im",
    stack: ["NextJS,ReactJS,HTML,CSS"],
    description: "This NextJS app serves the purpose of showcasing my projects",
  },
  {
    name: 'Portofolio V1',
    liveLink: "immm",
    gitLink: "imm",
    category: "web",
    image: "im",
    stack: ["HTML,CSS"],
    description: "This served the purpose of showcasing my projects",
  },
  {
    name: 'Smartbrain',
    liveLink: "immm",
    gitLink: "imm",
    category: "web",
    image: "im",
    stack: ["ReactJS,HTML,CSS,ExpressJS,Redis,JWT,Postgresql"],
    description: "This React app allows the user to signup, signin, upload an image to be used for demonstrating clarifi's facial recognition api, it also increases the user's score for each image uploaded. Redis is used to make the JWTs expire",
  },
  {
    name: 'Landing Page',
    liveLink: "immm",
    gitLink: "imm",
    category: "web",
    image: "im",
    stack: ["Javascript,HTML,CSS"],
    description: "Built this for FreeCodeCamp's Responsive Web Design Certification",
  },
  {
    name: 'Survey Form',
    liveLink: "immm",
    gitLink: "imm",
    category: "web",
    image: "im",
    stack: ["HTML,CSS"],
    description: "Built this for FreeCodeCamp's Responsive Web Design Certification",
  },
  {
    name: 'WebCrawler Hangman',
    liveLink: "immm",
    gitLink: "imm",
    category: "web",
    image: "im",
    stack: ["Python"],
    description: "This project consists of two python scripts, one that crawls an website for quotes and their author, storing them in a csv and the other script uses this csv to promt the user to play hangman to find the author,the user gets a variety of hints for each failed guessing attempt",
  },
]